services:
  app:
    build: .
    command: bash -c "bin/rails db:prepare && bin/rails s -b 0.0.0.0"
    environment:
      DATABASE_HOST: db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      RAILS_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: apolices_api_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
