default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>

development:
  <<: *default
  database: apolices_api_development

test:
  <<: *default
  database: apolices_api_test

production:
  <<: *default
  database: apolices_api_production
  username: apolices_api
  password: <%= ENV["APOLICES_API_DATABASE_PASSWORD"] %>
